import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { Link, Route, Routes, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import Admin from './pages/Admin';
import { ArrowRight, Search, ShoppingBag, Plus, Minus, X, Star, Leaf, Menu as MenuIcon, UserRound, Clock, ShieldCheck, Headphones, Truck } from 'lucide-react';
import axios from 'axios';

const API='https://nomnow-backend.onrender.com/api';
const CartContext=createContext(null);
const useCart=()=>useContext(CartContext);

const fallback=[
 {id:'1',name:'Firecracker Noodles',description:'Wok-tossed noodles, chilli crisp, scallions & sesame',price:149,category:'Noodles',image:'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=85',vegetarian:false,spiceLevel:'Hot',rating:4.9,time:20,badge:'SPICY'},
 {id:'2',name:'Golden Crunch Burger',description:'Crispy chicken, pickles, slaw & house sauce',price:179,category:'Burgers',image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',vegetarian:false,spiceLevel:'Medium',rating:4.8,time:25,badge:'BESTSELLER'},
 {id:'3',name:'Green Goddess Bowl',description:'Avocado, greens, grains, herbs & citrus dressing',price:169,category:'Veggie',image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Mild',rating:4.7,time:20,badge:'VEG'},
 {id:'4',name:'Farmhouse Pizza',description:'Tomato sauce, mozzarella, veggies & herbs',price:249,category:'Pizza',image:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Mild',rating:4.6,time:25,badge:'CHEESY'},
 {id:'5',name:'Korean Rice Bowl',description:'Rice, spicy chicken, kimchi, egg & veggies',price:199,category:'Rice',image:'https://assets.lummi.ai/assets/QmQhttr9xXzTAnFHX4SDf7pive9C6trEA5PFEoy6Mf3qgT',vegetarian:false,spiceLevel:'Hot',rating:4.8,time:30,badge:'SPICY'},
 {id:'6',name:'Chocolate Overload Cake',description:'Rich chocolate layers with silky choco glaze',price:129,category:'Desserts',image:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Mild',rating:4.9,time:15,badge:'SWEET'},
 {id:'7',name:'Midnight Ramen',description:'Rich broth, noodles, egg, mushrooms & chilli oil',price:199,category:'Noodles',image:'https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=1600&q=90',vegetarian:false,spiceLevel:'Hot',rating:4.8,time:25,badge:'HOT'},
 {id:'8',name:'Tomato Burst Pasta',description:'Creamy tomato sauce, parmesan & basil',price:169,category:'Pasta',image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Mild',rating:4.9,time:20,badge:'VEG'},
 {id:'9',name:'Crispy Bao Bites',description:'Soft bao, sticky tofu, cucumber & sesame',price:119,category:'Sides',image:'/assets/bao.jpeg',vegetarian:true,spiceLevel:'Medium',rating:4.6,time:15,badge:'VEG'},
 {id:'10',name:'Sunshine Tacos',description:'Citrus chicken, salsa, herbs & lime crema',price:159,category:'Sandwiches',image:'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=900&q=85',vegetarian:false,spiceLevel:'Medium',rating:4.8,time:20,badge:'FRESH'},
 {id:'11',name:'Paneer Tikka Wrap',description:'Smoky paneer, peppers, mint chutney & onions',price:139,category:'Sandwiches',image:'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Medium',rating:4.8,time:15,badge:'VEG'},
 {id:'12',name:'Masala Loaded Fries',description:'Crispy fries, masala dust, cheese & green chutney',price:109,category:'Sides',image:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Hot',rating:4.7,time:12,badge:'SPICY'},
 {id:'13',name:'Butter Chicken Bowl',description:'Creamy butter chicken, jeera rice & pickled onions',price:219,category:'Rice',image:'https://data.thefeedfeed.com/static/2019/08/29/15670911425d67e9c68e125.jpg',vegetarian:false,spiceLevel:'Medium',rating:4.9,time:30,badge:'FAVOURITE'},
 {id:'14',name:'Mango Lassi',description:'Thick mango yogurt drink with cardamom',price:89,category:'Drinks',image:'/assets/mango-lassi.jpeg',vegetarian:true,spiceLevel:'Mild',rating:4.8,time:8,badge:'SWEET'},
 {id:'15',name:'Gulab Jamun Cheesecake',description:'Creamy cheesecake, gulab jamun & saffron glaze',price:149,category:'Desserts',image:'https://indiaphile.info/wp-content/uploads/2022/12/stp-gulab-jamun-cheesecake-4284-2048x1365.jpg',vegetarian:true,spiceLevel:'Mild',rating:4.8,time:12,badge:'SWEET'},
 {id:'16',name:'Tandoori Paneer Pizza',description:'Tandoori paneer, onion, capsicum & mint drizzle',price:269,category:'Pizza',image:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Medium',rating:4.7,time:25,badge:'VEG'},
 {id:'17',name:'Chilli Paneer Rice',description:'Wok-fried rice, chilli paneer, spring onion & sesame',price:189,category:'Rice',image:'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1600&q=90',vegetarian:true,spiceLevel:'Hot',rating:4.7,time:25,badge:'SPICY'},
 {id:'18',name:'Masala Lemon Soda',description:'Fresh lime, soda, mint & a pinch of black salt',price:69,category:'Drinks',image:'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Mild',rating:4.7,time:5,badge:'FRESH'},
 {id:'19',name:'Smoky Paneer Burger',description:'Charred paneer patty, lettuce, onions & smoky mayo',price:159,category:'Burgers',image:'https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Medium',rating:4.7,time:20,badge:'VEG'},
 {id:'20',name:'Peri Peri Chicken Burger',description:'Crispy chicken, peri peri sauce, slaw & pickles',price:189,category:'Burgers',image:'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=85',vegetarian:false,spiceLevel:'Hot',rating:4.8,time:22,badge:'SPICY'},
 {id:'21',name:'Four Cheese Pizza',description:'Mozzarella, cheddar, parmesan & creamy cheese sauce',price:289,category:'Pizza',image:'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1600&q=90',vegetarian:true,spiceLevel:'Mild',rating:4.7,time:25,badge:'CHEESY'},
 {id:'22',name:'Chilli Garlic Noodles',description:'Garlic noodles, chilli oil, spring onion & sesame',price:139,category:'Noodles',image:'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Hot',rating:4.8,time:18,badge:'SPICY'},
 {id:'23',name:'Schezwan Noodles',description:'Wok-tossed noodles, peppers, cabbage & schezwan sauce',price:149,category:'Noodles',image:'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Hot',rating:4.7,time:20,badge:'HOT'},
 {id:'24',name:'Teriyaki Chicken Rice',description:'Sticky teriyaki chicken, steamed rice, greens & sesame',price:209,category:'Rice',image:'https://borner.ru/img/30min/%D0%BA%D1%83%D1%80%D0%B8%D1%86%D0%B0-%D1%82%D0%B5%D1%80%D0%B8%D1%8F%D0%BA%D0%B8_%D1%80%D0%B5%D1%86%D0%B5%D0%BF%D1%82.jpg',vegetarian:false,spiceLevel:'Medium',rating:4.8,time:28,badge:'FAVOURITE'},
 {id:'25',name:'Paneer Tikka Rice Bowl',description:'Grilled paneer tikka, rice, avocado, peppers & mint chutney',price:179,category:'Rice',image:'/assets/paneer-tikka-rice-bowl.jpeg',vegetarian:true,spiceLevel:'Medium',rating:4.7,time:25,badge:'VEG'},
 {id:'26',name:'Arrabbiata Pasta',description:'Tomato chilli sauce, garlic, basil & parmesan',price:159,category:'Pasta',image:'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Hot',rating:4.8,time:20,badge:'SPICY'},
 {id:'27',name:'Creamy Mushroom Pasta',description:'Creamy garlic sauce, mushrooms, herbs & parmesan',price:179,category:'Pasta',image:'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1600&q=90',vegetarian:true,spiceLevel:'Mild',rating:4.7,time:22,badge:'CREAMY'},
 {id:'28',name:'Peri Peri Fries',description:'Crispy fries, peri peri seasoning & house dip',price:99,category:'Sides',image:'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=1600&q=90',vegetarian:true,spiceLevel:'Hot',rating:4.7,time:12,badge:'SPICY'},
 {id:'29',name:'Cheese Garlic Bread',description:'Toasted garlic bread, mozzarella & herb butter',price:129,category:'Sides',image:'https://www.mathsya.co.in/wp-content/uploads/2023/03/garlic-bread.jpg',vegetarian:true,spiceLevel:'Mild',rating:4.8,time:12,badge:'CHEESY'},
  {id:'31',name:'Brownie Blast',description:'Warm chocolate brownie, fudge sauce & vanilla cream',price:119,category:'Desserts',image:'https://images.unsplash.com/photo-1619270298835-6681d172c02b?auto=format&fit=crop&w=1600&q=90',vegetarian:true,spiceLevel:'Mild',rating:4.9,time:10,badge:'SWEET'},
 {id:'32',name:'Lotus Biscoff Cheesecake',description:'Creamy cheesecake, Biscoff crumb & caramel drizzle',price:169,category:'Desserts',image:'https://juliemarieeats.com/wp-content/uploads/2023/02/Biscoff-Cheesecake-14-scaled.jpg',vegetarian:true,spiceLevel:'Mild',rating:4.8,time:12,badge:'SWEET'},
 {id:'33',name:'Strawberry Cooler',description:'Fresh strawberry, citrus, mint & sparkling soda',price:99,category:'Drinks',image:'/assets/strawberry-cooler.jpeg',vegetarian:true,spiceLevel:'Mild',rating:4.7,time:6,badge:'FRESH'},
 {id:'34',name:'Cold Coffee',description:'Iced coffee, creamy milk, vanilla & cocoa dust',price:109,category:'Drinks',image:'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=85',vegetarian:true,spiceLevel:'Mild',rating:4.8,time:7,badge:'FAVOURITE'}
];

const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;

function CartProvider({children}){
 const [items,setItems]=useState(()=>JSON.parse(localStorage.getItem('nomnow-cart')||'[]'));
 useEffect(()=>localStorage.setItem('nomnow-cart',JSON.stringify(items)),[items]);
 const add=item=>setItems(prev=>{const f=prev.find(x=>(x._id||x.id)===(item._id||item.id)); return f?prev.map(x=>(x._id||x.id)===(item._id||item.id)?{...x,quantity:x.quantity+1}:x):[...prev,{...item,quantity:1}];});
 const remove=id=>setItems(prev=>prev.filter(x=>(x._id||x.id)!==id));
 const change=(id,d)=>setItems(prev=>prev.map(x=>(x._id||x.id)===id?{...x,quantity:Math.max(1,x.quantity+d)}:x));
 const clear=()=>setItems([]);
 const count=items.reduce((s,x)=>s+x.quantity,0), subtotal=items.reduce((s,x)=>s+x.price*x.quantity,0), delivery=subtotal?49:0;
 return <CartContext.Provider value={{items,add,remove,change,clear,count,subtotal,delivery,total:subtotal+delivery}}>{children}</CartContext.Provider>
}

function Navbar(){
 const {count}=useCart(); const [open,setOpen]=useState(false); const [q,setQ]=useState(''); const nav=useNavigate();
 const go=(path)=>{setOpen(false);nav(path)};
 const submit=e=>{e.preventDefault();go(`/menu${q.trim()?`?q=${encodeURIComponent(q.trim())}`:''}`)};
 return <header className="nav">
  <Link className="logo" to="/" onClick={()=>setOpen(false)}><span>NOM</span><span>NOW</span><small>FOOD / LOUDLY</small></Link>
  <nav className={open?'mobile-open':''}>
   <Link to="/" onClick={()=>setOpen(false)}>HOME</Link><Link to="/menu" onClick={()=>setOpen(false)}>MENU</Link><Link to="/about" onClick={()=>setOpen(false)}>ABOUT</Link><Link to="/contact" onClick={()=>setOpen(false)}>CONTACT</Link>
  </nav>
  <div className="nav-actions">
   <form className="nav-search" onSubmit={submit}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search for food..."/><button aria-label="Search"><Search size={17}/></button></form>
   <Link to="/cart" className="bag" aria-label="Cart"><ShoppingBag size={20}/>{count>0&&<b>{count}</b>}</Link>
   <Link className="account" to="/login"><UserRound size={15}/> ACCOUNT</Link>
   <button className="hamb" onClick={()=>setOpen(!open)} aria-label="Open menu"><MenuIcon/></button>
  </div>
 </header>
}

function FoodCard({item}){const {add}=useCart(); return <article className="food-card">
 <div className="food-img"><img src={item.image} alt={item.name}/>{item.badge&&<span className={`food-badge ${item.badge==='VEG'?'veg-badge':''}`}>{item.badge}</span>}<span className="tag">{item.category}</span></div>
 <div className="food-info"><h3>{item.name}</h3><p>{item.description}</p><div className="food-meta"><span><Star size={13} fill="currentColor"/> {item.rating}</span><span className="time"><Clock size={13}/> {item.time||20} min</span></div><div className="food-buy"><strong>{money(item.price)}</strong><button className="add-btn" onClick={()=>add(item)}><Plus size={16}/> ADD</button></div></div>
 </article>}

function CategoryStrip({active='ALL',onSelect}){const cats=[['ALL','▦'],['BURGERS','🍔'],['PIZZA','🍕'],['NOODLES','🍜'],['RICE','🍚'],['PASTA','🍝'],['SANDWICHES','🥪'],['SIDES','🍟'],['DESSERTS','🍰'],['DRINKS','🥤'],['VEGGIE','🌿'],['SPICY','🌶️']]; return <div className="category-strip">{cats.map(([name,icon])=><button className={active===name?'active':''} onClick={()=>onSelect?.(name)} key={name}><span>{icon}</span>{name}</button>)}</div>}

const mergeFoods=(remote=[])=>{ const byName=new Map(fallback.map(x=>[x.name.toLowerCase(),x])); remote.forEach(x=>{ if(x?.name && !byName.has(x.name.toLowerCase())) byName.set(x.name.toLowerCase(),x); }); return [...byName.values()]; };

function Home(){const [foods,setFoods]=useState(fallback); const [hotIndex,setHotIndex]=useState(0); const [hotDirection,setHotDirection]=useState('next'); useEffect(()=>{axios.get(API+'/food').then(r=>r.data?.length&&setFoods(mergeFoods(r.data))).catch(()=>{})},[]); const popular=foods.slice(0,6); const hotItems=foods.filter(x=>['Midnight Ramen','Golden Crunch Burger','Firecracker Noodles','Butter Chicken Bowl','Paneer Rice Bowl'].includes(x.name)); const hotList=hotItems.length?hotItems:foods; const hot=hotList[hotIndex%hotList.length]||foods[0]; const prevHot=()=>{setHotDirection('prev');setHotIndex(i=>(i-1+hotList.length)%hotList.length)}; const nextHot=()=>{setHotDirection('next');setHotIndex(i=>(i+1)%hotList.length)}; return <>
 <section className="hero-ref">
  <div className="hero-ref-copy"><p className="eyebrow">GOOD FOOD. NO BORING.</p><h1><span>GOOD FOOD.</span><strong>NO WAIT.</strong></h1><p className="hero-sub">Big flavors. Bold bites.<br/>Delivered hot to your door.</p><div className="hero-actions"><Link className="primary" to="/menu">ORDER NOW <ArrowRight size={18}/></Link><Link className="explore-link" to="/menu">EXPLORE MENU</Link></div></div>
  <div className="hero-ref-art"><div className="hero-burst pink-burst">✦</div><div className="hero-burst yellow-burst">✦</div><img key={hot?.id||hot?._id||hotIndex} className={`hot-dish-image ${hotDirection}`} src={hot?.image||foods[0]?.image} alt={hot?.name||'Featured NOMNOW dish'}/><div className="hot-card"><p>HOT RIGHT NOW</p><h3>{hot?.name||'Spicy Ramen'}</h3><strong>{money(hot?.price||199)}</strong><div><button type="button" aria-label="Previous hot item" onClick={prevHot}>←</button><button type="button" aria-label="Next hot item" onClick={nextHot}>→</button></div></div><div className="made-for">✦<br/><small>MADE FOR<br/>BIG CRAVINGS</small></div></div>
 </section>
 <CategoryStrip onSelect={cat=>cat==='ALL'?document.getElementById('popular')?.scrollIntoView({behavior:'smooth'}):navToMenu(cat)}/>
 <section className="section popular-section" id="popular"><div className="section-title-row"><h2><span className="starburst-mini">✦</span> POPULAR PICKS</h2><Link to="/menu" className="view-all">VIEW ALL <ArrowRight size={16}/></Link></div><div className="popular-grid">{popular.map(x=><FoodCard key={x._id||x.id} item={x}/>)}</div></section>
 <section className="loud-banner"><div><small>CRAVING<br/>SOMETHING</small><strong>LOUD?</strong><ArrowRight/></div><p>We've got bold flavors for<br/>every mood and every craving.</p><Link to="/menu" className="pink-btn">FEED ME NOW <ArrowRight size={17}/></Link><div className="pepper">🌶️</div></section>
 <Benefits/><Footer/>
 </>}
function navToMenu(cat){window.location.href=`/menu?cat=${encodeURIComponent(cat)}`}

function Benefits(){return <section className="benefits"><div><Truck/><strong>FAST DELIVERY</strong><span>30 mins at your door</span></div><div><ShieldCheck/><strong>SAFE & SECURE</strong><span>100% secure payments</span></div><div><Leaf/><strong>BEST QUALITY</strong><span>Fresh ingredients daily</span></div><div><Headphones/><strong>LIVE SUPPORT</strong><span>We're here for you</span></div><div className="newsletter-mini"><p>GET THE GOOD STUFF</p><span>Exclusive offers, new drops & more.</span><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Enter your email" required/><button>JOIN</button></form></div></section>}

function Menu(){const [foods,setFoods]=useState(fallback),[q,setQ]=useState(''),[cat,setCat]=useState('ALL'); const [params]=useSearchParams(); useEffect(()=>{const initialQ=params.get('q')||'';const initialCat=params.get('cat')||'ALL';setQ(initialQ);setCat(initialCat.toUpperCase());axios.get(API+'/food').then(r=>r.data?.length&&setFoods(mergeFoods(r.data))).catch(()=>{})},[params]); const shown=foods.filter(x=>{const normalized=x.category.toUpperCase(); const catMatch=cat==='ALL'||normalized===cat||(cat==='VEGGIE'&&x.vegetarian)||(cat==='SPICY'&&x.spiceLevel==='Hot'); return catMatch&&(x.name+' '+x.description).toLowerCase().includes(q.toLowerCase())}); return <><div className="menu-hero"><div><p className="eyebrow">THE FULL MENU</p><h1>EAT<br/><span>LOUD.</span></h1></div><div className="menu-search"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your craving..."/></div></div><section className="section menu-section"><CategoryStrip active={cat} onSelect={setCat}/><div className="food-grid menu-grid">{shown.map(x=><FoodCard key={x._id||x.id} item={x}/>)}</div>{!shown.length&&<div className="empty">NOTHING HERE.<br/><span>YET.</span></div>}</section><Footer/></>}

function ContentPage({type}){if(type==='about')return <><section className="editorial about-page"><div><p className="eyebrow">WHY NOMNOW?</p><h1>FOOD<br/><span>SHOULD</span><br/>HAVE A<br/>PERSONALITY.</h1></div><div className="editorial-copy"><p>We make ordering feel less like a transaction and more like finding your new favorite thing.</p><p>NOMNOW is built for big cravings, quick decisions and food worth talking about. Pick a mood, find your thing, and get it to your door without the boring bits.</p><div className="editorial-stats"><b>08<small>BIG CATEGORIES</small></b><b>24/7<small>CRAVING SUPPORT</small></b><b>30<small>MIN DELIVERY</small></b></div></div></section><Footer/></>;
 if(type==='flavors')return <><section className="flavor-page"><div className="flavor-title"><p className="eyebrow">TONIGHT'S MOOD</p><h1>FLAVOR<br/><span>ATTACK.</span></h1></div><div className="flavor-copy"><h2>SPICY.<br/>SWEET.<br/>A LITTLE<br/>MESSY.</h2><p>Find the food that matches the mood. Hot, crispy, creamy, cheesy, fresh — NOMNOW keeps the flavor loud.</p><Link className="primary" to="/menu">FEED ME <ArrowRight/></Link></div><div className="flavor-image"><img src={fallback[0].image} alt="Noodles"/></div></section><Footer/></>;
 return <><section className="contact-page"><p className="eyebrow">SAY HELLO</p><h1>LET'S<br/><span>TALK FOOD.</span></h1><div className="contact-grid"><div><h3>NEED A HAND?</h3><p>hello@nomnow.in</p><p>+91 98765 43210</p></div><div><h3>WE'RE HERE</h3><p>Monday — Sunday<br/>11:00 AM — 11:00 PM</p></div><form onSubmit={e=>{e.preventDefault();alert('Thanks! The NOMNOW team will get back to you.')}}><input placeholder="Your name" required/><input type="email" placeholder="Your email" required/><textarea placeholder="What's cooking?" rows="4" required/><button className="primary full">SEND IT <ArrowRight/></button></form></div></section><Footer/></>}

function Cart(){const c=useCart(); const nav=useNavigate(); return <><div className="page-banner small"><p className="eyebrow">YOUR ORDER</p><h1>CART<br/><span>CHECK.</span></h1></div><section className="cart-layout section">{!c.items.length?<div className="empty cart-empty">YOUR CART IS<br/><span>HUNGRY.</span><Link className="primary" to="/menu">GO EAT <ArrowRight/></Link></div>:<><div className="cart-items">{c.items.map(x=><div className="cart-item" key={x._id||x.id}><img src={x.image} alt=""/><div><p className="eyebrow">{x.category}</p><h3>{x.name}</h3><p>{x.description}</p><div className="qty"><button onClick={()=>c.change(x._id||x.id,-1)}><Minus size={15}/></button><b>{x.quantity}</b><button onClick={()=>c.change(x._id||x.id,1)}><Plus size={15}/></button></div></div><strong>{money(x.price*x.quantity)}</strong><button className="remove" onClick={()=>c.remove(x._id||x.id)}><X/></button></div>)}</div><aside className="summary"><p className="eyebrow">THE DAMAGE</p><h2>ORDER<br/>TOTAL</h2><div><span>SUBTOTAL</span><b>{money(c.subtotal)}</b></div><div><span>DELIVERY</span><b>{money(c.delivery)}</b></div><div className="total"><span>TOTAL</span><b>{money(c.total)}</b></div><button className="primary full" onClick={()=>nav('/checkout')}>CHECKOUT <ArrowRight/></button><button className="clear" onClick={c.clear}>CLEAR CART</button></aside></>}</section><Footer/></>}

function Checkout(){const c=useCart(),[loading,setLoading]=useState(false),[message,setMessage]=useState(''); const pay=async()=>{setLoading(true); try { const r=await axios.post(API+'/payments/create-checkout-session',{items:c.items}); if(r.data.url) window.location.href=r.data.url; else setMessage(r.data.message); } catch(e){setMessage(e.response?.data?.message||'Payment service unavailable.');} finally{setLoading(false)} }; return <><div className="page-banner small"><p className="eyebrow">LAST STEP</p><h1>LET'S<br/><span>NOM.</span></h1></div><section className="checkout section"><div className="form-box"><p className="eyebrow">DELIVERY DETAILS</p><h2>WHERE ARE<br/>WE GOING?</h2><div className="form-grid"><input placeholder="Full name"/><input placeholder="Phone number"/><input placeholder="Email"/><input placeholder="Apartment / Flat"/><input className="wide" placeholder="Street address"/><input placeholder="City"/><input placeholder="PIN code"/></div><p className="micro">Stripe checkout is securely handled by Stripe. Add your Stripe secret key in <code>server/.env</code> to enable live test payments.</p></div><aside className="summary"><p className="eyebrow">FINAL BILL</p><h2>{money(c.total)}</h2><div>{c.items.length} item{c.items.length!==1?'s':''}<span>incl. delivery</span></div><button disabled={!c.items.length||loading} className="primary full" onClick={pay}>{loading?'OPENING STRIPE...':'PAY WITH STRIPE'} <ArrowRight/></button>{message&&<p className="error">{message}</p>}</aside></section><Footer/></>}

function Login(){const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[msg,setMsg]=useState(''); const submit=async e=>{e.preventDefault();try{const r=await axios.post(API+`/auth/${mode}`,form);localStorage.setItem('nomnow-token',r.data.token);localStorage.setItem('nomnow-user',JSON.stringify(r.data.user));setMsg("YOU'RE IN.");}catch(e){setMsg(e.response?.data?.message||'Try again.')}}; return <><div className="auth"><div className="auth-art"><div className="giant">NOM<br/><span>NOW</span></div><p>FOOD WITH<br/>A POINT OF VIEW.</p></div><form className="auth-form" onSubmit={submit}><p className="eyebrow">{mode==='login'?'WELCOME BACK':'JOIN THE TABLE'}</p><h1>{mode==='login'?'LOGIN.':'SIGN UP.'}</h1>{mode==='register'&&<input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary full">{mode==='login'?'LET ME IN':'CREATE ACCOUNT'} <ArrowRight/></button>{msg&&<p className="success">{msg}</p>}<button type="button" className="switch" onClick={()=>setMode(mode==='login'?'register':'login')}><span>{mode==='login'?'NEW TO NOMNOW?':'ALREADY A MEMBER?'}</span><b>{mode==='login'?'SIGN UP':'LOG IN'} <ArrowRight size={14}/></b></button></form></div></>}

function Footer(){return <footer><div className="footer-logo">NOM<span>NOW</span></div><div><p className="eyebrow">SHOP</p><Link to="/menu">Menu</Link><Link to="/menu">Categories</Link><Link to="/menu?cat=SPICY">Offers</Link></div><div><p className="eyebrow">INFO</p><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/contact">Delivery</Link></div><div className="newsletter"><p className="eyebrow">GET THE GOOD STUFF</p><h3>NO SPAM.<br/>JUST SNACKS.</h3><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="your@email.com" required/><button>JOIN</button></form></div><div className="footer-bottom">© 2026 NOMNOW · FOOD / LOUDLY <span>MADE FOR BIG CRAVINGS.</span></div></footer>}

export default function App(){return <CartProvider><Navbar/><Routes><Route path="/" element={<Home/>}/><Route path="/menu" element={<Menu/>}/><Route path="/about" element={<ContentPage type="about"/>}/><Route path="/contact" element={<ContentPage type="contact"/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/login" element={<Login/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<Home/>}/></Routes></CartProvider>}
